config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "companies#index"

  get "recentworks(/:days)" => "works#index"
  get "timetrackerproject(/:slug)" => "projects#show"

  resources :companies
  resources :projects
  resources :works

end

app/models/work.rb
class Work < ActiveRecord::Base
  belongs_to :project
  belongs_to :user

  validates :project, presence: true
  validates :user, presence: true
  validates :datetimeperformed, presence: true
  validate :date_performed_is_in_past
  validates :hours, numericality: 
                    { only_integer: true, 
                      greater_than: 0,
                      less_than_or_equal_to: 8 }


  scope :fullday, -> { where("hours >= 8") }

  #scope :recent, -> { where("datetimeperformed > '#{Time.now - 7.days}'") }
  def self.recentdays(num_days_ago)
    since_date = Time.now - num_days_ago.to_i.days
    where("datetimeperformed > '#{since_date}'")
  end

  def to_s
    #"Performed on #{work.datetimeperformed} by #{work.user.name} for #{work.project.name}"    
    "#{user}: #{datetimeperformed.strftime('%m/%m/%Y %H:%M')} - #{hours} hours"
  end

  private

    def date_performed_is_in_past
      if datetimeperformed.present? && datetimeperformed > Time.now
        errors.add(:datetimeperformed, "can't be in the future.")
      end
    end

end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create]

  def index
    if params[:days]
      @works = Work.recentdays(params[:days]).order("datetimeperformed DESC").paginate(page: params[:page])
    else
      @works = Work.all.order("datetimeperformed DESC").paginate(page: params[:page])
    end
  end

  def show
    @work = Work.find(params[:id])
  end

  def new
    @work = Work.new
  end

  def create
    @work = Work.new(work_params)
    @work.user = current_user

    if params[:doc]
      uploaded_io = params[:doc]
      @work.doc = uploaded_io.original_filename   
      File.open(Rails.root.join("public", "uploads", uploaded_io.original_filename), "wb") do |file|
        file.write(uploaded_io.read)
        @work.doc = uploaded_io.original_filename
      end
    end
    respond_to do |format|
      if @work.save
        Usermailer.workcreated_email(@work).deliver_now
        format.html { redirect_to @work, notice: "Work Created" }
        format.js { }
      else
        format.html { render "new" }
        format.js { }
      end
    end
  end

  def edit
    @work = Work.find(params[:id])
  end

  def update
    @work = Work.find(params[:id])
    @work.user = current_user

    if params[:doc]
      uploaded_io = params[:doc]
      @work.doc = uploaded_io.original_filename   
      File.open(Rails.root.join("public", "uploads", uploaded_io.original_filename), "wb") do |file|
        file.write(uploaded_io.read)
        @work.doc = uploaded_io.original_filename
      end
    end

    if @work.update(work_params)
      flash[:notice] = "Work Updated"
      redirect_to @work
    else
      render "edit"
    end
  end  

  private
    def work_params
      params.require(:work).permit(:project_id, :datetimeperformed, :hours)
    end

    def set_current_user
      self.user = current_user
    end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/_form.html.erb
<% if @work.errors.any? %>
  <div id="errors">
    <p>Please correct the following <%= pluralize(@work.errors.count, "error") %>:</p>
    <ul>
      <% @work.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<% doajax = false unless (defined? doajax) %>
<%= form_for(@work, remote: doajax, html: { multipart: true }) do |f| %>
  <div>
    <%= f.label :project %>
    <%= f.collection_select(:project_id, Project.all, :id, :name, prompt: true) %>
  </div>
  <!-- <div> -->
    <%#= f.label :user %>
    <%#= f.collection_select(:user_id, User.all.order("lname, fname"), :id, :to_s, prompt: true) %>
  <!-- </div> -->
  <div>
    <%= f.label :datetimeperformed, "Date/Time Performed" %>
    <%= f.datetime_select :datetimeperformed %>
  </div>
  <div>
    <%= f.label :hours %>
    <%= f.select(:hours, [1, 2, 3, 4, 5, 6, 7, 8], prompt: true) %>
  </div>
  <% if !doajax %>
    <div>
      <%= label_tag :doc, "Notes (optional)" %>
      <%= file_field_tag :doc %>
    </div>
  <% end %>
  <div>
    <%= f.submit @work.new_record? ? "Create Work" : "Update Work" %>
  </div>
<% end %>

app/views/works/_sidebar.html.erb
<ul>
  <li><%= link_to "All Works", works_path %></li>
  <li><%= link_to "New Work", new_work_path %></li>
</ul>

app/views/works/_work.html.erb
<tr>
  <td><%= link_to "View", work %></td>  
  <td><%= work.user %></td>
  <td><%= link_to work.project, work.project %></td>
  <td><%= work.datetimeperformed.strftime('%m/%d/%Y %H:%M') %></td>
  <td><%= work.hours %></td>
</tr>

app/views/works/create.js.erb
<% if @work.errors.any? %>
  $('div#errors').remove();
  $('<div id="errors"><p>Please correct the following <%= pluralize(@work.errors.count, "error") %>:</p><ul><% @work.errors.full_messages.each do |msg| %><li><%= msg %></li><% end %></ul></div>').insertBefore('div.remoteform h2');
<% else %>
  $('div#errors').remove();
  $('<tr><td><%= link_to 'View', @work %></td><td><%= @work.user %></td><td><%= link_to @work.project, @work.project %></td><td><%= @work.datetimeperformed.strftime("%m/%d/%Y %H:%M") %></td><td><%= @work.hours %></td></tr>').insertAfter('tr#headerrow');
<% end %>

app/views/works/edit.html.erb
<h1>Edit Work</h1>

<%= render "form" %>

<% content_for :aside do %>
  <%= render "sidebar" %>
<% end %>

app/views/works/index.html.erb
<h1>Works: index</h1>
<p>Heare are all of the work items:</p>

<table>
  <tbody>
    <tr>
      <th>View</th>      
      <th>User</th>
      <th>Project</th>      
      <th>Date Time Performed</th>
      <th>Hours</th>
    </tr>
    <%= render partial: "work", collection: @works %>
  </tbody>
</table>
<%= will_paginate @works %>

<% content_for :aside do %>
  <% render "sidebar" %>
<% end %>

app/views/works/new.html.erb
<h1>New Work</h1>

<%= render "form" %>

<% content_for :aside do %>
  <%= render "sidebar" %>
<% end %>

app/views/works/show.html.erb
<h1>Work Item <%= @work.id %></h1>
<table>
  <tr>
    <th align="left">Project</th>
    <td><%= @work.project.name %></td>
  </tr>
  <tr>
    <th align="left">User</th>
    <td><%= @work.user %></td>
  </tr>
  <tr>
    <th align="left">Date Performed</th>
    <td><%= @work.datetimeperformed %></td>
  </tr>
  <tr>
    <th align="left">Hours</th>
    <td><%= @work.hours %></td>
  </tr>
  <% if @work.doc %>
    <tr>
      <th align="left">Document</th>
      <td><%= link_to @work.doc, "/uploads/#{@work.doc}", target: "_blank" %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "Edit Work", edit_work_path(@work) %></p>

<% content_for :aside do %>
  <% render "sidebar" %>
<% end %>