config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "companies#index"

  get "recentworks(/:days)" => "works#index"
  get "timetrackerproject(/:slug)" => "projects#show"

  resources :companies
  resources :projects
  resources :works

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :company
  has_many :works
  has_many :users, :through => :works
  belongs_to :owner, class_name: "User"

  validates :name, presence: true,
                   length: { minimum: 5 }
  validates :company, presence: true
  validates :default_rate, numericality: 
                           { only_integer: true,
                             greater_than_or_equal_to: 50,
                             less_than: 1000 }
  validates :slug, length: { minimum: 3 }                             
  validates :slug, uniqueness: true
  validates :owner, presence: true

  scope :lowdefaultrate, -> { where("default_rate < 100")}

  def to_s
    "#{name} (#{company})"
  end

  def self.export_csv(projects)
    CSV.generate do |csv|
      #csv << column_names
      csv << ["name", "company", "default_rate", "created_at", "owner", "most recent work item"]
      projects.each do |project|
        #csv << project.attributes.values_at(*column_names)
        csv << [
          project.name,
          project.company.name,
          project.default_rate,
          project.created_at,
          project.user,
          project.works.order("created_at DESC").first ]
      end
    end
  end  
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @projects = Project.all
    respond_to do |format|
      format.html { }
      format.csv { send_data Project.export_csv(@projects), type: "text/csv; charset=utf-8; header=present", disposition: "attachment; filename=projects.csv" }
    end    
  end

  def show
    if params[:slug]
      @project = Project.find_by slug: params[:slug]
    else
      @project = Project.find(params[:id])
    end
    @work = Work.new
    @work.project = @project
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project Created" }
        format.js { }
      else
        format.html { render "new" }
        format.js { }
      end
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      Usermailer.project_updated_email(@project).deliver
      flash[:notice] = "Project Updated"
      redirect_to @project
    else
      render "edit"
    end
  end

  private
    def project_params
      params.require(:project).permit(:name, :company_id, :default_rate, :slug, :owner_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<% if @project.errors.any? %>
  <div id="errors">
    <p>Please correct the following <%= pluralize(@project.errors.count, "error") %>:</p>
    <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @project do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name, size: 30 %>
  </div>
  <div>
    <%= f.label :slug %>
    <%= f.text_field :slug, size: 30 %>
  </div>
  <div>
    <%= f.label :default_rate %>
    <%= f.text_field :default_rate, size: 5 %>
  </div>
  <div>
    <%= f.label :company %>
    <%= f.collection_select(:company_id, Company.all.order("name"), :id, :name, prompt: true) %>
  </div>
  <div>
    <%= f.label :owner %>
    <%= f.collection_select(:owner_id, User.all.order("lname, fname"), :id, :to_s, prompt: true) %>
  </div>
  <div>
    <%= f.submit @project.new_record? ? "Create Project" : "Update Project" %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<tr>
  <td><%= link_to project, project %></td>
  <td><%= link_to project.company.name, project.company %></td>
</tr>

app/views/projects/_sidebar.html.erb
<ul>
  <li><%= link_to "All Projects", projects_path %></li>
  <li><%= link_to "New Project", new_project_path %></li>
</ul>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render "form" %>

<% content_for :aside do %>
  <%= render "sidebar" %>
<% end %>

app/views/projects/index.html.erb
<h1>Projects: index</h1>
<p>Heare are all of the projects:</p>
<table>
  <tbody>
    <tr>
      <th>Project</th>
      <th>Company</th>
    </tr>
    <%= render partial: "project", collection: @projects %>
  </tbody>
</table>

<% content_for :aside do %>
  <% render "sidebar" %>
<% end %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render "form" %>

<% content_for :aside do %>
  <%= render "sidebar" %>
<% end %>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>
<table>
  <tr>
    <th align="left">Company</th>
    <td><%= @project.company.name %></td>
  </tr>
  <tr>
    <th align="left">Default Rate</th>
    <td><%= number_to_currency(@project.default_rate) %></td>
  </tr>
  <tr>
    <th align="left">Slug</th>
    <td><%= @project.slug %></td>
  </tr>
  <tr>
    <th align="left">Owner</th>
    <td><%= @project.owner %></th>
  </tr>
</table>

<p><%= link_to "Edit Project", edit_project_path(@project) %>

<div class="remoteform">
  <h2>Add Work</h2>
  <%= render partial: "works/form", locals: { doajax: true } %>
</div>  

<% if @project.works.size > 0 %>
  <table>
    <tbody>
      <tr id="headerrow">
        <th>View</th>        
        <th>User</th>
        <th>Project</th>              
        <th>Date/Time Performed</th>
        <th>Hours</th>
      </tr>
      <%= render partial: "works/work", collection: @project.works %>
    </tbody>
  </table>
<% else %>
  <p>No work items</p>
<% end %>  

<% content_for :aside do %>
  <% render "sidebar" %>
<% end %>