config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "companies#index"

  get "recentworks(/:days)" => "works#index"
  get "timetrackerproject(/:slug)" => "projects#show"

  resources :companies
  resources :projects
  resources :works

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :users
  has_many :projects

  validates :name, presence: true, 
                   length: { minimum: 5 }  

  def to_s
    name
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_filter :confirm_admin, only: [:new, :create, :edit, :update]

  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render xml: @company }
      format.json { render json: @company } 
    end   
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      flash[:notice] = "Company Created"
      redirect_to @company
    else
      render "new"
    end
  end  

def edit
  @company = Company.find(params[:id])
end

def update
  @company = Company.find(params[:id])
  if @company.update(company_params)
    flash[:notice] = "Company Updated"
    redirect_to @company
  else
    render "edit"
  end
end


private
  def company_params
    params.require(:company).permit(:name)
  end  

  def confirm_admin
    unless current_user.admin?
      redirect_to companies_path, :alert => "Only admins can create/modify a company"
      return false
    else
      return true
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.html.erb
<tr>
  <td><%= link_to company, company %></td>
</tr>

app/views/companies/_form.html.erb
<% if @company.errors.any? %>
  <div id="errors">
    <p>Please correct the following <%= pluralize(@company.errors.count, "error") %>:</p>
    <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @company do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.submit @company.new_record? ? "Create Company" : "Update Company" %>
  </div>
<% end %>

app/views/companies/_sidebar.html.erb
<ul>
  <li><%= link_to "All Companies", companies_path %></li>
  <li><%= link_to "New Company", new_company_path %></li>
</ul>

app/views/companies/edit.html.erb
<h1>Edit Company</h1>

<%= render "form" %>

<% content_for :aside do %>
  <%= render "sidebar" %>
<% end %>

app/views/companies/index.html.erb
<h1>Companies: index</h1>
<p>Here are all of the companies:</p>

<table>
  <tbody>
    <tr>
      <th>Company Name</th>
    </tr>
    <%= render partial: "company", collection: @companies %>
  </tbody>
</table>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render "form" %>

<% content_for :aside do %>
  <%= render "sidebar" %>
<% end %>

app/views/companies/show.html.erb
<h1><%= @company.name %></h1>

<p><%= link_to "Edit Company", edit_company_path(@company) %></p>

<% if @company.projects.size > 0 %>
  <table>
    <tbody>
      <tr>
        <th>Project</th>
        <th>Company</th>
      </tr>
      <%= render partial: "projects/project", collection: @company.projects %>
    </tbody>
  </table>
<% else %>
  <p>No projects</p>
<% end %>  

<% content_for :aside do %>
  <%= render partial: "sidebar" %>
<% end %>